name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Test Coverage
        env: # Or as an environment variable
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          API_URL: ${{ secrets.API_URL }}
        # run: REPORT_GAS=true npx hardhat test
        run: npx hardhat coverage --testfiles test/Ticket.js
      - name: Linters
        run: solhint 'contracts/**/*.sol'
